### ISSUE TITLE
Endless recursion if method has its surrounding class as return type

### ISSUE THREAD

**Issue by fbenz** [raphaeljolivet/java2typescript#3]
I expect the following Java code
```java
class Test {
  public Test returnThis() {
    return this;
  }
}
```

to result in the following TypeScript code
```typescript
export interface Test {
  returnThis(): Test
}
```
However, the converter fails with a stack overflow.

**Comment by atsu85** [comment]
@fbenz, FYI, i noticed [Your workaround](https://github.com/fbenz/java2typescript/commit/75850b650c1c74c7dddd4327da215e45004025d7) for this issue, that just didn't add recursive methods to generated output. I made a [proper fix](https://github.com/atsu85/java2typescript/commit/d7018b1455c514df0f9a80afe9875dbb2a4158ec) for this issue.

**Comment by atsu85** [comment]
I also added [a test](https://github.com/atsu85/java2typescript/commit/89c3ec23d8191b0890bfc6abef2302db512e332c) that reproduced this issue (and confirms it is fixed), but unfortunately I couldn't use Your (minimal) example, because class without fields is currently not added to output - i created separate issue for that: #20
